import type { Metadata } from "next";
import { Calistoga } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import TawkTo from "@/services/TawkTo";
import LogRocket from "@/services/LogRocket";
import Navbar from "@/components/Shared/Navbar";
import Footer from "@/components/Shared/Footer";
import GoogleAnalytics from "@/services/GoogleAnalytics";
import { preloadGlobalData } from "@/controllers/globalController";

export const dynamic = "force-dynamic";


const calistoga = Calistoga({
  variable: "--font-calistoga",
  subsets: ["latin"],
  weight: "400",
  display: "swap",
});

const gilroy = localFont({
  src: [
    {
      path: "./fonts/Gilroy-Light_0.ttf",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/Gilroy-Regular_0.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/Gilroy-Medium_0.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/Gilroy-SemiBold_0.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "./fonts/Gilroy-Bold_0.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-gilroy",
  display: "swap",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        suppressHydrationWarning
        className={`${calistoga.variable} ${gilroy.className} antialiased bg-[#29252D] text-white transition-colors duration-300 overflow-y-auto
  [&::-webkit-scrollbar]:w-1.5
  [&::-webkit-scrollbar-thumb]:rounded-[50px]
  [&::-webkit-scrollbar-track]:bg-gray-100
  [&::-webkit-scrollbar-thumb]:bg-pink-500
  `
}
      >
        <Navbar />


        <TawkTo />
        <GoogleAnalytics gaId={process.env.NEXT_PUBLIC_GA_ID} />
        <LogRocket />
        {children}
        <Footer />
      </body>
    </html>
  );
}

// Call this during app initialization
preloadGlobalData();
